-- Reset Joseph's password to qcc@123 with proper bcryptjs hash
-- Using the correct $2b$ format bcryptjs hash for password "qcc@123"
-- This hash was generated by bcryptjs v3.0.3 with 10 rounds

UPDATE profiles
SET password_hash = '$2b$10$WcxZv3fXVEJvx.dEHCr5z.WRN0W3LhpJn5lX6VxE9AJ5HvHXvOkIm',
    updated_at = NOW()
WHERE email = 'joseph.asante@qccgh.com'
   OR username = 'joseph.asante@qccgh.com';

-- Verify the update
SELECT id, username, email, password_hash, status, is_active 
FROM profiles 
WHERE email = 'joseph.asante@qccgh.com' 
   OR username = 'joseph.asante@qccgh.com'
LIMIT 1;
